### ISSUE TITLE
Upgrade to Spider 0.0.5

### ISSUE THREAD

**Issue by alongubkin** [mariusc23/grunt-spider-script#1]
Since Spider now depends on this plugin, the build (https://travis-ci.org/alongubkin/spider) is failing because it uses Spider 0.0.4. Can you upgrade it to 0.0.5?

Thanks!

**Comment by mariusc23** [comment]
Cool! I mean, that you're using my plugin, not that the build is failing. Should be good to go now. I was hoping the semver caret would do it, but it seems like it doesn't take into effect until 0.1.x.

**Comment by alongubkin** [comment]
Aweosme, [looks like it worked](https://travis-ci.org/alongubkin/spider/builds/41627170). Thanks! Your plugin is great btw, you should write it in Spider ;)

**Comment by alongubkin** [comment]
but it doesn't work for newer versions of spider (0.0.7)

**Comment by mariusc23** [comment]
Thanks! Should be good for 0.0.7 now. I'll look into setting a less strict semver so you don't have to wait on me to update the plugin.

**Comment by alongubkin** [comment]
Spider 0.1.0 released

**Comment by mariusc23** [comment]
Sweet! Looks like there's quite a bit of logic in the cli now. I was trying to get it to run through that instead of importing spider.js manually so I don't have to duplicate a lot of code. This way users could also use their globally installed version of spider if they want to.

Can you add an option to specify a destination? Otherwise the compiled js and map files will have to be in the same directory for the sourcemap urls to point at the right location. Also, I noticed the sourcemap URLs are different for ES5 vs ES6. For ES6 it uses absolute paths.

**Comment by alongubkin** [comment]
I think it's best if I make the CLI as simple as possible and add its functionality to spider.spider.

**Comment by alongubkin** [comment]
Okay, fixed in 0.1.3. Please note that the `spider.compile` has been refactored. It will be documented soon.

Usage:

```
var out = spider.compile({
  text: "var x = 5;",
  fileName: "test.spider",
  target: "ES5", // (or "ES6")
  generateSourceMap: true
});
```

The `out` object has 3 properties: `errors`, `result` and `sourceMap`.

To print errors, you can use the `spider.formatErrors` API. For example:

```
console.log(spider.formatErrors("test.spider", "var x = 5;", out.errors));
```

**Comment by mariusc23** [comment]
Awesome! I updated the plugin to 0.1.3. The error formatting is really sweet!

Right now the plugin doesn't work because it fails to import spider-script. I think it's because in `package.json` you have `"main": "lib/spider-script.js"`, which doesn't exist. It should probably point to `lib/spider.js`.

**Comment by alongubkin** [comment]
Oops, fixed in 0.1.4.

BTW: It should actually point to spider-script.js, which avoids you from having to `require("traceur")` or `require("traceur-runtime")`.

**Comment by mariusc23** [comment]
Okay, good to know. I'll remove the traceur dependency. Seems like the import is still failing. It looks like npm doesn't check out the `spider-script.js` file. Maybe you have to add it to the files array?

**Comment by alongubkin** [comment]
Yeah. Should work now (0.1.5).

**Comment by mariusc23** [comment]
It's all good now!

**Comment by alongubkin** [comment]
Awesome!
